default_platform(:ios)

platform :ios do

  desc "Create app on App Store Connect"
  lane :create_app do
    produce(
      app_identifier: "com.driver.bestseed",
      app_name: "Drive Bestseed",
      language: "English",
      app_version: "1.0.2",
      sku: "com.driver.bestseed",
      enable_services: {
        push_notification: "on"
      }
    )
  end

  desc "Upload metadata and screenshots to App Store Connect"
  lane :metadata do
    upload_to_app_store(
      skip_binary_upload: true,
      skip_app_version_update: true,
      force: true,
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        export_compliance_uses_encryption: false,
        content_rights_contains_third_party_content: false,
        content_rights_has_rights: true,
        add_id_info_uses_idfa: false
      }
    )
  end

  desc "Build the Flutter iOS app"
  lane :build do
    Dir.chdir("../..") do
      sh("flutter build ipa --release")
    end
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    upload_to_testflight(
      ipa: "../../build/ios/ipa/Drive Bestseed.ipa",
      skip_waiting_for_build_processing: true
    )
  end

  desc "Upload to App Store (binary + metadata)"
  lane :release do
    build
    upload_to_app_store(
      ipa: "../../build/ios/ipa/Drive Bestseed.ipa",
      skip_screenshots: true,
      submit_for_review: false,
      force: true,
      submission_information: {
        export_compliance_uses_encryption: false,
        content_rights_contains_third_party_content: false,
        content_rights_has_rights: true,
        add_id_info_uses_idfa: false
      }
    )
  end

end
